name: Build FRP-Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 配置 JDK
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. 配置 Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # 4. 可选：解码 keystore
      - name: Decode keystore
        if: secrets.KEYSTORE_BASE64 != ''
        run: |
          echo "$KEYSTORE_BASE64" | base64 --decode > release.keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}

      # 5. 构建 APK
      - name: Build Release APK
        env:
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
        run: |
          chmod +x ./gradlew
          ./gradlew assembleRelease

      # 6. 上传 APK
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: frp-android-release
          path: app/build/outputs/apk/release/*.apk

      # 7. 创建 GitHub Release（可选）
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: app/build/outputs/apk/release/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
